export const GET_USER_CHATS_REQUEST = "GET_USER_CHATS_REQUEST"
export const GET_USER_CHATS_SUCCESS = "GET_USER_CHATS_SUCCESS"
export const GET_USER_CHATS_FAIL = "GET_USER_CHATS_FAIL"
export const GET_USER_CHATS_RESET = "GET_USER_CHATS_RESET"

export const GET_SINGLE_CHAT_REQUEST = "GET_SINGLE_CHAT_REQUEST"
export const GET_SINGLE_CHAT_SUCCESS = "GET_SINGLE_CHAT_SUCCESS"
export const GET_SINGLE_CHAT_FAIL = "GET_SINGLE_CHAT_FAIL"

export const CREATE_CHAT_REQUEST = "CREATE_CHAT_REQUEST"
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS"
export const CREATE_CHAT_FAIL = "CREATE_CHAT_FAIL"
export const CREATE_CHAT_RESET = "CREATE_CHAT_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"