export const SEND_FOLLOW_UNFOLLOW_REQUEST = "SEND_FOLLOW_UNFOLLOW_REQUEST"
export const SEND_FOLLOW_UNFOLLOW_SUCCESS = "SEND_FOLLOW_UNFOLLOW_SUCCESS"
export const SEND_FOLLOW_UNFOLLOW_FAIL = "SEND_FOLLOW_UNFOLLOW_FAIL"
export const SEND_FOLLOW_UNFOLLOW_RESET = "SEND_FOLLOW_UNFOLLOW_RESET"

export const ACCEPT_FOLLOW_REQUEST = "ACCEPT_FOLLOW_REQUEST"
export const ACCEPT_FOLLOW_SUCCESS = "ACCEPT_FOLLOW_SUCCESS"
export const ACCEPT_FOLLOW_FAIL = "ACCEPT_FOLLOW_FAIL"

export const REMOVE_FOLLOWER_FROM_FOLLOWERS_REQUEST = "REMOVE_FOLLOWER_FROM_FOLLOWERS_REQUEST"
export const REMOVE_FOLLOWER_FROM_FOLLOWERS_SUCCESS = "REMOVE_FOLLOWER_FROM_FOLLOWERS_SUCCESS"
export const REMOVE_FOLLOWER_FROM_FOLLOWERS_FAIL = "REMOVE_FOLLOWER_FROM_FOLLOWERS_FAIL"
export const REMOVE_FOLLOWER_FROM_FOLLOWERS_RESET = "REMOVE_FOLLOWER_FROM_FOLLOWERS_RESET"

export const CANCEL_FOLLOW_REQUEST = "CANCEL_FOLLOW_REQUEST"
export const CANCEL_FOLLOW_SUCCESS = "CANCEL_FOLLOW_SUCCESS"
export const CANCEL_FOLLOW_FAIL = "CANCEL_FOLLOW_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"
