export const REQUESTED_USER_PROFILE_REQUEST = "REQUESTED_USER_PROFILE_REQUEST";
export const REQUESTED_USER_PROFILE_SUCCESS = "REQUESTED_USER_PROFILE_SUCCESS";
export const REQUESTED_USER_PROFILE_FAIL = "USER_PROFILE_FAIL";

export const CLEAR_ERRORS ="CLEAR_ERRORS"