export const CREATE_NEW_POST_REQUEST = "CREATE_NEW_POST_REQUEST";
export const CREATE_NEW_POST_SUCCESS = "CREATE_NEW_POST_SUCCESS";
export const CREATE_NEW_POST_FAIL = "CREATE_NEW_POST_FAIL";
export const CREATE_NEW_POST_RESET = "CREATE_NEW_POST_RESET"

export const GET_LOGGED_USER_POST_REQUEST = "GET_LOGGED_USER_POST_REQUEST";
export const GET_LOGGED_USER_POST_SUCCESS = "GET_LOGGED_USER_POST_SUCCESS";
export const GET_LOGGED_USER_POST_FAIL = "GET_LOGGED_USER_POST_FAIL";

export const DELETE_LOGGED_USER_POST_REQUEST = "DELETE_LOGGED_USER_POST_REQUEST";
export const DELETE_LOGGED_USER_POST_SUCCESS = "DELETE_LOGGED_USER_POST_SUCCESS";
export const DELETE_LOGGED_USER_POST_FAIL = "DELETE_LOGGED_USER_POST_FAIL";
export const DELETE_LOGGED_USER_POST_RESET = "DELETE_LOGGED_USER_POST_RESET";

export const UPDATE_LOGGED_USER_POST_REQUEST = "UPDATE_LOGGED_USER_POST_REQUEST";
export const UPDATE_LOGGED_USER_POST_SUCCESS = "UPDATE_LOGGED_USER_POST_SUCCESS";
export const UPDATE_LOGGED_USER_POST_FAIL = "UPDATE_LOGGED_USER_POST_FAIL";
export const UPDATE_LOGGED_USER_POST_RESET = "UPDATE_LOGGED_USER_POST_RESET";

export const GET_LIKES_USERS_REQUEST = "GET_LIKES_USERS_REQUEST"
export const GET_LIKES_USERS_SUCCESS = "GET_LIKES_USERS_SUCCESS"
export const GET_LIKES_USERS_FAIL = "GET_LIKES_USERS_FAIL"

export const GET_POST_DETAILS_REQUEST = "GET_POST_DETAILS_REQUEST"
export const GET_POST_DETAILS_SUCCESS = "GET_POST_DETAILS_SUCCESS"
export const GET_POST_DETAILS_FAIL = "GET_POST_DETAILS_FAIL"

export const GET_POST_COMMENTS_REQUEST = "GET_POST_COMMENTS_REQUEST"
export const GET_POST_COMMENTS_SUCCESS = "GET_POST_COMMENTS_SUCCESS"
export const GET_POST_COMMENTS_FAIL = "GET_POST_COMMENTS_FAIL"

export const POSTING_COMMENT_REQUEST = "POSTING_COMMENT_REQUEST"
export const POSTING_COMMENT_SUCCESS = "POSTING_COMMENT_SUCCESS"
export const POSTING_COMMENT_FAIL = "POSTING_COMMENT_FAIL"
export const POSTING_COMMENT_RESET = "POSTING_COMMENT_RESET"

export const POSTING_REPLIES_ON_COMMENT_REQUEST = "POSTING_REPLIES_ON_COMMENT_REQUEST"
export const POSTING_REPLIES_ON_COMMENT_SUCCESS = "POSTING_REPLIES_ON_COMMENT_SUCCESS"
export const POSTING_REPLIES_ON_COMMENT_FAIL = "POSTING_REPLIES_ON_COMMENT_FAIL"
export const POSTING_REPLIES_ON_COMMENT_RESET = "POSTING_REPLIES_ON_COMMENT_RESET"

export const POST_COMMENT_DELETE_REQUEST = "POST_COMMENT_DELETE_REQUEST"
export const POST_COMMENT_DELETE_SUCCESS = "POST_COMMENT_DELETE_SUCCESS"
export const POST_COMMENT_DELETE_FAIL = "POST_COMMENT_DELETE_FAIL"
export const POST_COMMENT_DELETE_RESET = "POST_COMMENT_DELETE_RESET"

export const DELETE_REPLY_OF_COMMENT_REQUEST = "DELETE_REPLY_OF_COMMENT_REQUEST"
export const DELETE_REPLY_OF_COMMENT_SUCCESS = "DELETE_REPLY_OF_COMMENT_SUCCESS"
export const DELETE_REPLY_OF_COMMENT_FAIL = "DELETE_REPLY_OF_COMMENT_FAIL"
export const DELETE_REPLY_OF_COMMENT_RESET = "DELETE_REPLY_OF_COMMENT_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"
