export const GET_TIMELINE_POST_REQUEST = "GET_TIMELINE_POST_REQUEST"
export const GET_TIMELINE_POST_SUCCESS = "GET_TIMELINE_POST_SUCCESS"
export const GET_TIMELINE_POST_FAIL = "GET_TIMELINE_POST_FAIL"

export const DO_LIKE_REQUEST = "DO_LIKE_REQUEST"
export const DO_LIKE_SUCCESS = "DO_LIKE_SUCCESS"
export const DO_LIKE_FAIL = "DO_LIKE_FAIL"
export const DO_LIKE_RESET = "DO_LIKE_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"
