export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_RESET = "LOGIN_RESET";

export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAIL = "REGISTRATION_FAIL";
export const REGISTRATION_RESET = "REGISTRATION_RESET";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const USER_EDIT_PROFILE_REQUEST = "USER_EDIT_PROFILE_REQUEST";
export const USER_EDIT_PROFILE_SUCCESS = "USER_EDIT_PROFILE_SUCCESS";
export const USER_EDIT_PROFILE_FAIL = "USER_EDIT_PROFILE_FAIL";
export const USER_EDIT_PROFILE_RESET = "USER_EDIT_PROFILE_RESET";

export const GET_RESET_PASSWORD_LINK_REQUEST = "GET_RESET_PASSWORD_LINK_REQUEST";
export const GET_RESET_PASSWORD_LINK_SUCCESS = "GET_RESET_PASSWORD_LINK_SUCCESS";
export const GET_RESET_PASSWORD_LINK_FAIL = "GET_RESET_PASSWORD_LINK_FAIL";
export const GET_RESET_PASSWORD_LINK_RESET = "GET_RESET_PASSWORD_LINK_RESET";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_RESET = "RESET_PASSWORD_RESET";

export const USER_EDIT_AVATAR_REQUEST = "USER_EDIT_AVATAR_REQUEST";
export const USER_EDIT_AVATAR_SUCCESS = "USER_EDIT_AVATAR_SUCCESS";
export const USER_EDIT_AVATAR_FAIL = "USER_EDIT_AVATAR_FAIL";
export const USER_EDIT_AVATAR_RESET = "USER_EDIT_AVATAR_RESET";

export const USER_UPDATE_PROFILE_STATUS_REQUEST = "USER_UPDATE_PROFILE_STATUS_REQUEST";
export const USER_UPDATE_PROFILE_STATUS_SUCCESS = "USER_UPDATE_PROFILE_STATUS_SUCCESS";
export const USER_UPDATE_PROFILE_STATUS_FAIL = "USER_UPDATE_PROFILE_STATUS_FAIL";
export const USER_UPDATE_PROFILE_STATUS_RESET = "USER_UPDATE_PROFILE_STATUS_RESET";

export const USER_EDIT_PERSONEL_INFORMATION_REQUEST = "USER_EDIT_PERSONEL_INFORMATION_REQUEST";
export const USER_EDIT_PERSONEL_INFORMATION_SUCCESS = "USER_EDIT_PERSONEL_INFORMATION_SUCCESS";
export const USER_EDIT_PERSONEL_INFORMATION_FAIL = "USER_EDIT_PERSONEL_INFORMATION_FAIL";
export const USER_EDIT_PERSONEL_INFORMATION_RESET = "USER_EDIT_PERSONEL_INFORMATION_RESET";

export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAIL = "SEARCH_USER_FAIL";
export const SEARCH_USER_RESET = "SEARCH_USER_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS"